Add error filter
BBVAEngineering/ember-cli-bugsnag pull request #29
Opened 2020-02-06 12:54 UTC by angelmr98

2020-02-10 13:33 UTC, adrigzr requested changes

2020-02-10 13:33 UTC, adrigzr commented on app/instance-initializers/bugsnag.js
> +			errorFilter
This is not necessary. You can use `appMethods.filterError`

2020-02-10 13:33 UTC, adrigzr commented on app/instance-initializers/bugsnag.js
> +		if (!error || this.errorFilter.includes(error.name)) {
This is not good, you should call the function directly.

```suggestion
		if (!error || !appMethods.errorFilter(error)) {
```

2020-02-10 13:33 UTC, adrigzr commented on app/instance-initializers/bugsnag.js
> +		if (typeof error !== 'object' || !error.name || !error.message) {
This is not longer needed. It was removed on `master`.

2020-02-10 13:33 UTC, adrigzr commented on tests/acceptance/bugsnag-test.js
> +	test('it does not notify a filtered error', async function(assert) {
This test is not working properly. You need to stub de `errorFilter` method.

2020-02-11 11:32 UTC, adrigzr approved these changes

2020-02-11 13:42 UTC, eumendoza approved these changes

2020-02-11 14:29 UTC, merged

2020-02-11 14:40 UTC, adrigzr commented
:tada: This PR is included in version 3.1.0 :tada:

The release is available on [GitHub release](https://github.com/BBVAEngineering/ember-cli-bugsnag/releases/tag/v3.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: